# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275aedd5430edb1e578d8c4ce42d1cdcffb3bcdc5a5986491ce310c2d863cde09daf033cd6464b18fc9a2a7bf764e19b05c7ea98fb00c6310b231eb7dff81f21

test:
  secret_key_base: 0566e18c820caa12a7c78db9ca206951600d4ca7f7fa27328b83582cd78ba7f1b20b58c1be5964f296ea8033e050e9efc910d94486d25008e1a329decc4efb17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
